"""
Higgsfield Agent — auto-triggers AI asset generation for newly submitted queue items.

Runs every 30s. Picks up any item with:
  - status = 'pending_review'
  - higgsfield_status = 'idle' or 'failed'
and starts the full generation pipeline in a background thread.

This means any item submitted via CLI or auto-generated by the content agent
will get its intro video, thumbnail, and scenes without touching the dashboard.
"""
from __future__ import annotations
import threading
from rich.console import Console
from src.agents.base import Agent
from src.youtube.queue import list_content, set_higgsfield_status, set_higgsfield_assets

console = Console()

_generating: set[str] = set()
_lock = threading.Lock()


class HiggsFieldAgent(Agent):
    name = "higgsfield-agent"
    interval_seconds = 30

    def tick(self) -> None:
        items = list_content(status="pending_review")
        for item in items:
            cid = item["id"]
            hf_status = item.get("higgsfield_status", "idle")
            if hf_status not in ("idle", "failed"):
                continue
            with _lock:
                if cid in _generating:
                    continue
                _generating.add(cid)
            t = threading.Thread(
                target=_run_generation,
                args=(cid, item["title"]),
                daemon=True,
                name=f"hf-gen-{cid[:8]}",
            )
            t.start()
            console.print(f"[cyan]higgsfield-agent:[/cyan] started generation for '{item['title'][:50]}'")


def _run_generation(content_id: str, title: str) -> None:
    try:
        set_higgsfield_status(content_id, "generating")
        from src.higgsfield.generator import generate_all_assets
        assets = generate_all_assets(content_id, title)
        set_higgsfield_assets(
            content_id,
            assets["intro_path"],
            assets["thumbnail_path"],
            assets["scenes_paths"],
        )
        console.print(f"[green]higgsfield-agent:[/green] assets ready for '{title[:50]}'")
    except Exception as exc:
        set_higgsfield_status(content_id, "failed", str(exc))
        console.print(f"[red]higgsfield-agent: generation failed for {content_id[:8]}: {exc}[/red]")
    finally:
        with _lock:
            _generating.discard(content_id)
